const kenyaHotels = [
    {
      image:"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/ce/53/24/all-50-rooms-are-thoughtfully.jpg?w=300&h=300&s=1",
      name: "Savannah Paradise Hotel",
      location: "Nairobi",
      stars: 5,
      ratings: 4.8,
    },
    {
      image:"https://cf.bstatic.com/xdata/images/hotel/square600/64918103.webp?k=cf49d26382a2410e670f2401a6492eeda732c7d542877db2060893b29c6ba9a3&o=",
      name: "Serena Beach Resort & Spa",
      location: "Mombasa",
      stars: 5,
      ratings: 4.7,
    },
    {
      image:"https://cdn.worldota.net/t/1024x768/content/c1/59/c159948be0ce995213585ca148069fc1474cdeb5.jpeg",
      name: "Aberdare Country Lodge",
      location: "Aberdare National Park",
      stars: 4,
      ratings: 4.3,
    },
    {
      image:"https://www.sopalodges.com/images/amboseli/monkey-at-amboseli-sopa-lodge.jpg",
      name: "Amboseli Sopa Lodge",
      location: "Amboseli National Park",
      stars: 4,
      ratings: 4.4,
    },
    {
      image:"https://www.sopalodges.com/images/masai-mara/pool-and-lodge.jpg",
      name: "Maasai Mara Sopa Lodge",
      location: "Maasai Mara",
      stars: 4,
      ratings: 4.5,
    },
    {
      image:"https://www.sopalodges.com/images/naivasha/swimming-pool-and-gardens.jpg",
      name: "Lake Naivasha Resort",
      location: "Lake Naivasha",
      stars: 3,
      ratings: 4.0,
    },
    {
      image:"https://sncdn.com/imagecache/db/id/1683920/471412a.jpg",
      name: "Tsavo River Lodge",
      location: "Tsavo National Park",
      stars: 3,
      ratings: 4.1,
    },
    {
      image:"https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_225,q_auto,w_225/hotelier-images/cc/8c/08801016c68886c4a920d8e7565ef98fe100d7470c51f53324c61ead561b.jpeg",
      name: "Diani Sea Lodge",
      location: "Diani Beach",
      stars: 4,
      ratings: 4.6,
    },
    {
      image:"https://imgcy.trivago.com/c_limit,d_dummy.jpeg,f_auto,h_1300,q_auto,w_2000/uploadimages/83/58/8358331.jpeg",
      name: "Nakuru Lake Lodge",
      location: "Lake Nakuru",
      stars: 3,
      ratings: 4.2,
    },
    {
      image:"https://www.heritage-eastafrica.com/greatriftvalleylodgeandgolfresort/media/great-rift-valley-lodge-and-golf-resort-imageLinkimg_7452.jpg",
      name: "Great Rift Valley Lodge & Golf Resort",
      location: "Naivasha",
      stars: 4,
      ratings: 4.5,
    },
    {
      image:"https://oltukailodge.com/wp-content/uploads/wedding_banner2.jpg",
      name: "Ol Tukai Lodge",
      location: "Amboseli National Park",
      stars: 3,
      ratings: 4.0,
    },
    {
      image:"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/b1/a8/1a/treetops-exterior-evening.jpg?w=2400&h=-1&s=1",
      name: "Treetops Lodge",
      location: "Aberdare National Park",
      stars: 4,
      ratings: 4.4,
    },
    {
      image:"https://www.sarovahotels.com/stanley-nairobi/assets/images/experiences-gallery1.jpg",
      name: "Sarova Stanley",
      location: "Nairobi",
      stars: 5,
      ratings: 4.7,
    },
    {
      image:"https://image-tc.galaxy.tf/wijpeg-aimbeydhu3lgarfv27sc5ba3b/069-mara-suite.jpg?width=684&height=378",
      name: "Mara Serena Safari Lodge",
      location: "Maasai Mara",
      stars: 5,
      ratings: 4.9,
    },
    {
      image:"https://cf.bstatic.com/xdata/images/hotel/square600/57942966.webp?k=bd27121ba8cf7119533f7ca93e3ce26c06ae38a3cec724a0f4d82b2c19b71362&o=",
      name: "Voyager Beach Resort",
      location: "Mombasa",
      stars: 4,
      ratings: 4.5,
    },
    {
      image:"https://www.leopardbeachresort.com/images/banner/837f1808c3d2ea0f6b3860bded48d7ee.jpg",
      name: "Leopard Beach Resort & Spa",
      location: "Diani Beach",
      stars: 5,
      ratings: 4.8,
    },
    {
      image:"https://www.tafaria.com/assets/img/Home%20Carousel3.jpg",
      name: "Tafaria Castle and Country Lodge",
      location: "Nyeri",
      stars: 4,
      ratings: 4.4,
    },
    {
      image:"https://cf.bstatic.com/xdata/images/hotel/square200/311505151.webp?k=ac6f04080a72bde18a007c6e68fa2cc631b2441124f3fd35c6919fc11703a125&o=",
      name: "Hemingways Nairobi",
      location: "Nairobi",
      stars: 5,
      ratings: 4.8,
    },
    {
      image:"https://www.heritage-eastafrica.com/maraintrepids/media/mara-intrepids-gallerymic0811-79.jpg",
      name: "Mara Intrepids Luxury Tented Camp",
      location: "Maasai Mara",
      stars: 4,
      ratings: 4.6,
    },
    
  ];
  export default kenyaHotels;
  

  